In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer

corpus = [
    " thor eating pizza, loki is eating pizza, steve is eating pasta",
    " iron man  is eating pasta", "Apple is launching new iphon",
    "Samsung is launching new galaxy" ,
    "tesla announced new car tomorrow",
    "amazon anouncing new eco-dot tomorrow",
    "google launching new pixel phone tomorrow",
    "microsoft launching new surface tomorrow"
]

v = TfidfVectorizer()

In [2]:
v = TfidfVectorizer()
v.fit(corpus)
transform_output = v.transform(corpus)
transform_output = v.transform(corpus)
print(v.vocabulary_)

{'thor': 26, 'eating': 6, 'pizza': 21, 'loki': 14, 'is': 12, 'steve': 23, 'pasta': 18, 'iron': 11, 'man': 15, 'apple': 3, 'launching': 13, 'new': 17, 'iphon': 10, 'samsung': 22, 'galaxy': 8, 'tesla': 25, 'announced': 1, 'car': 4, 'tomorrow': 27, 'amazon': 0, 'anouncing': 2, 'eco': 7, 'dot': 5, 'google': 9, 'pixel': 20, 'phone': 19, 'microsoft': 16, 'surface': 24}


In [4]:
v.vocabulary_.get('thor') # 26 index

26

In [8]:
# print the idf of each word
all_feature_names = v.get_feature_names_out()

for word in all_feature_names:

  indx = v.vocabulary_.get(word)

  #get the score
  idf_score = v.idf_[(indx)]

  print(f"{word} : {idf_score}")

amazon : 2.504077396776274
announced : 2.504077396776274
anouncing : 2.504077396776274
apple : 2.504077396776274
car : 2.504077396776274
dot : 2.504077396776274
eating : 2.09861228866811
eco : 2.504077396776274
galaxy : 2.504077396776274
google : 2.504077396776274
iphon : 2.504077396776274
iron : 2.504077396776274
is : 1.587786664902119
launching : 1.587786664902119
loki : 2.504077396776274
man : 2.504077396776274
microsoft : 2.504077396776274
new : 1.251314428280906
pasta : 2.09861228866811
phone : 2.504077396776274
pixel : 2.504077396776274
pizza : 2.504077396776274
samsung : 2.504077396776274
steve : 2.504077396776274
surface : 2.504077396776274
tesla : 2.504077396776274
thor : 2.504077396776274
tomorrow : 1.587786664902119


In [9]:
#print the transformed output from tf-idf
print(transform_output.toarray())

[[0.         0.         0.         0.         0.         0.
  0.63591448 0.         0.         0.         0.         0.
  0.32075054 0.         0.25292572 0.         0.         0.
  0.21197149 0.         0.         0.50585144 0.         0.25292572
  0.         0.         0.25292572 0.        ]
 [0.         0.         0.         0.         0.         0.
  0.42954038 0.         0.         0.         0.         0.51253028
  0.32498546 0.         0.         0.51253028 0.         0.
  0.42954038 0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.57223943 0.         0.
  0.         0.         0.         0.         0.57223943 0.
  0.36284587 0.36284587 0.         0.         0.         0.2859542
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.57223943 0.         0.        

In [ ]:
# datasetlink - "https://www.kaggle.com/datasets/saurabhshahane/ecommerce-text-classification"#

In [24]:
import pandas as pd
import numpy as np

In [14]:

df = pd.read_csv(r"/content/sample_data/ecommerceDataset.csv",)

In [16]:
df.head(14)

Household  \
0   Household   
1   Household   
2   Household   
3   Household   
4   Household   
5   Household   
6   Household   
7   Household   
8   Household   
9   Household   
10  Household   
11  Household   
12  Household   
13  Household   

   Paper Plane Design Framed Wall Hanging Motivational Office Decor Art Prints (8.7 X 8.7 inch) - Set of 4 Painting made up in synthetic frame with uv textured print which gives multi effects and attracts towards it. This is an special series of paintings which makes your wall very beautiful and gives a royal touch. This painting is ready to hang, you would be proud to possess this unique painting that is a niche apart. We use only the most modern and efficient printing technology on our prints, with only the and inks and precision epson, roland and hp printers. This innovative hd printing technique results in durable and spectacular looking prints of the highest that last a lifetime. We print solely with top-notch 100% inks, to achieve brilliant and true colours. Due to their high level of uv resistance, our prints retain their beautiful colours for many years. Add colour and style to your living space with this digitally printed painting. Some are for pleasure and some for eternal bliss.so bring home this elegant print that is lushed with rich colors that makes it nothing but sheer elegance to be to your friends and family.it would be treasured forever by whoever your lucky recipient is. Liven up your place with these intriguing paintings that are high definition hd graphic digital prints for home, office or any room.  
0   SAF 'Floral' Framed Painting (Wood, 30 inch x ...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
1   SAF 'UV Textured Modern Art Print Framed' Pain...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               

In [17]:
df.shape

(50424, 2)

In [21]:
df.columns

Index(['Household', 'Paper Plane Design Framed Wall Hanging Motivational Office Decor Art Prints (8.7 X 8.7 inch) - Set of 4 Painting made up in synthetic frame with uv textured print which gives multi effects and attracts towards it. This is an special series of paintings which makes your wall very beautiful and gives a royal touch. This painting is ready to hang, you would be proud to possess this unique painting that is a niche apart. We use only the most modern and efficient printing technology on our prints, with only the and inks and precision epson, roland and hp printers. This innovative hd printing technique results in durable and spectacular looking prints of the highest that last a lifetime. We print solely with top-notch 100% inks, to achieve brilliant and true colours. Due to their high level of uv resistance, our prints retain their beautiful colours for many years. Add colour and style to your living space with this digitally printed painting. Some are for pleasure and s

In [26]:
df[df.columns[0]].value_counts()

Household
Household                 19312
Books                     11820
Electronics               10621
Clothing & Accessories     8671
Name: count, dtype: int64

In [29]:
df['label_num'] = df[df.columns[0]].map({
    'Household':0,
    'Electronics':1,
    'Clothing & Accessories':2,
    'Books':3,
}) #classes no's

In [54]:
df.tail(20)

Household  \
50404  Electronics   
50405  Electronics   
50406  Electronics   
50407  Electronics   
50408  Electronics   
50409  Electronics   
50410  Electronics   
50411  Electronics   
50412  Electronics   
50413  Electronics   
50414  Electronics   
50415  Electronics   
50416  Electronics   
50417  Electronics   
50418  Electronics   
50419  Electronics   
50420  Electronics   
50421  Electronics   
50422  Electronics   
50423  Electronics   

      Paper Plane Design Framed Wall Hanging Motivational Office Decor Art Prints (8.7 X 8.7 inch) - Set of 4 Painting made up in synthetic frame with uv textured print which gives multi effects and attracts towards it. This is an special series of paintings which makes your wall very beautiful and gives a royal touch. This painting is ready to hang, you would be proud to possess this unique painting that is a niche apart. We use only the most modern and efficient printing technology on our prints, with only the and inks and precision epson, roland and hp printers. This innovative hd printing technique results in durable and spectacular looking prints of the highest that last a lifetime. We print solely with top-notch 100% inks, to achieve brilliant and true colours. Due to their high level of uv resistance, our prints retain their beautiful colours for many years. Add colour and style to your living space with this digitally printed painting. Some are for pleasure and some for eternal bliss.so bring home this elegant print that is lushed with rich colors that makes it nothing but sheer elegance to be to your friends and family.it would be treasured forever by whoever your lucky recipient is. Liven up your place with these intriguing paintings that are high definition hd graphic digital prints for home, office or any room.  \
50404  Kechaoda K33 Slim Card Size Light Weight and S...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
50405  Apple MK0C2ZM/A Pencil for Apple iPad Pro (Whi...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          

**trin test split**

In [35]:
from sklearn.model_selection import train_test_split

x_train , x_test , y_train , y_test = train_test_split(df[df.columns[1]],df['label_num'],test_size=0.2,random_state=42)

In [37]:
len(x_train),len(x_test)

(40339, 10085)

**Tfidf vectorizer**

In [39]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Fill missing values with empty strings
x_train = x_train.fillna('')
x_test = x_test.fillna('')


tf = TfidfVectorizer()
x_train_tf = tf.fit_transform(x_train)
x_test_tf = tf.transform(x_test)

**Classifier model**

In [40]:
from sklearn.tree import DecisionTreeClassifier

clf = DecisionTreeClassifier()
clf.fit(x_train_tf,y_train)

y_pred = clf.predict(x_test_tf)

In [44]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix

# Calculate evaluation metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')

# Print the metrics
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-Score: {f1:.4f}")

Accuracy: 0.9483
Precision: 0.9484
Recall: 0.9483
F1-Score: 0.9483


In [45]:
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.94      0.95      0.95      3874
           1       0.95      0.93      0.94      2082
           2       0.94      0.96      0.95      1750
           3       0.97      0.95      0.96      2379

    accuracy                           0.95     10085
   macro avg       0.95      0.95      0.95     10085
weighted avg       0.95      0.95      0.95     10085

[[3682   84   54   54]
 [ 103 1946   16   17]
 [  58    9 1672   11]
 [  68   18   29 2264]]


**Testing on new data**

In [46]:
msg = "Contrast living Decorative box "

msg_tf = tf.transform([msg])

clf.predict(msg_tf)

array([0])

In [47]:
msg = "Contrast living cusioun box "

msg_tf = tf.transform([msg])

clf.predict(msg_tf)

array([0])

In [48]:
msg = "Contrast living TV and setupbox "

msg_tf = tf.transform([msg])

clf.predict(msg_tf)

array([3])

 Household':0,
'Electronics':1,
Clothing & Accessories':2,
'Books':3,

In [55]:
msg = "Micromax Canvas Win W121 (White)	 "

msg_tf = tf.transform([msg])

clf.predict(msg_tf)

array([1])

In [53]:
msg = "TP-Link TL-WN725N 150Mbps Wireless N Nano USB "

msg_tf = tf.transform([msg])

clf.predict(msg_tf)

array([1])

****