In [1]:
#importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


In [2]:
#mounting the google collab
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
df = pd.read_csv(r"sample_data/Churn_Modelling.csv")

In [4]:
df.head()


RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [6]:
x = df.iloc[:,3:13].values
y = df.iloc[:,13].values

In [7]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [8]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [9]:
x.shape

(10000, 10)

In [10]:
y.shape

(10000,)

In [11]:
# Encoding categorical feature
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_x_1 = LabelEncoder()
x[:,1] = labelencoder_x_1.fit_transform(x[:,1])
labelencoder_x_2 = LabelEncoder()
x[:,2] = labelencoder_x_2.fit_transform(x[:,2])
x

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [12]:
#spliting dataset  into training ansd testing

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 0)

In [13]:
len(df)

10000

In [16]:
len(x_test)
len(x_train)

8000

In [17]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [18]:
#classical ml
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [24]:
# Train a Decisiontree model
classifier = DecisionTreeClassifier()
classifier.fit(x_train, y_train)

# Predict the test set results
pred = classifier.predict(x_test)

In [25]:
#Making confusion matrix

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, pred)
print(cm)

[[1358  237]
 [ 190  215]]


In [26]:
#mAKING  confusion matrix
from sklearn.metrics import accuracy_score
accuracy_score(y_test,pred)

0.7865

**Logistic regression**

In [27]:
# Train a Logistic Regression model
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)

# Predict the test set results
pred = classifier.predict(x_test)

#Making confusion matrix

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, pred)
print(cm)

# Acc score
from sklearn.metrics import accuracy_score
accuracy_score(y_test,pred)

[[1542   53]
 [ 333   72]]


0.807

In [29]:
# Train a KNeighbours model
classifier = KNeighborsClassifier()
classifier.fit(x_train, y_train)

# Predict the test set results
pred = classifier.predict(x_test)

#Making confusion matrix

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, pred)
print(cm)

# Acc score
from sklearn.metrics import accuracy_score
accuracy_score(y_test,pred)

[[1496   99]
 [ 232  173]]


0.8345

In [30]:
# Train a random forest model
classifier = RandomForestClassifier()
classifier.fit(x_train, y_train)

# Predict the test set results
pred = classifier.predict(x_test)

#Making confusion matrix

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, pred)
print(cm)

# Acc score
from sklearn.metrics import accuracy_score
accuracy_score(y_test,pred)

[[1532   63]
 [ 203  202]]


0.867

In [31]:
# Train a svc model
classifier = SVC()
classifier.fit(x_train, y_train)

# Predict the test set results
pred = classifier.predict(x_test)

#Making confusion matrix

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, pred)
print(cm)

# Acc score
from sklearn.metrics import accuracy_score
accuracy_score(y_test,pred)

[[1560   35]
 [ 239  166]]


0.863

**Ann model**

In [32]:
!pip install keras
!pip install tensorflow

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 620.7/620.7 MB 809.5 kB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 5.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.5/24.5 MB 108.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 65.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 157.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.5/224.5 kB 22.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.5/72.5 kB 7.7 MB/s eta 0:00:00


In [33]:
#import keras libraries
import keras
from keras.models import Sequential
from keras.layers import Dense

/usr/local/lib/python3.12/dist-packages/jax/_src/cloud_tpu_init.py:86: UserWarning: Transparent hugepages are not enabled. TPU runtime startup and shutdown time should be significantly improved on TPU v5e and newer. If not already set, you may need to enable transparent hugepages in your VM image (sudo sh -c "echo always > /sys/kernel/mm/transparent_hugepage/enabled")
  warnings.warn(


In [34]:
#initialize Ann
classifier = Sequential()

#units : its art comes by experience, input+output/2
#initializer : how your weights are updated
#relu activation function
#input dim: i/p sahape od data , how many featrure do we have in our data
#adding inputlayer and hidden layers
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 10)) #10 features so 10 input dim
#unit = 6 means 6 neurons , 2nd and 3rd also 6 and in final - 1 neuron hence clear its binary classification
#how decides 6 units - 10 input dim+ 1 last layer unit = 11/2 which is something around 5.5 = 6
#kernel = uniform means weights are in uniform


#Adding second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

#Adding Third hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

#Adding output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [35]:
#compile Ann
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
#for non binary callsification - use categoricacross_entropy or sparkcategoricalcross_entropy

#fitting the Ann to training set
classifier.fit(x_train, y_train, batch_size = 10, epochs = 200)


Epoch 1/200
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 808us/step - accuracy: 0.7887 - loss: 0.5693
Epoch 2/200
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 838us/step - accuracy: 0.7937 - loss: 0.4359
Epoch 3/200
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 855us/step - accuracy: 0.7961 - loss: 0.4198
Epoch 4/200
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 848us/step - accuracy: 0.8281 - loss: 0.4206
Epoch 5/200
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 822us/step - accuracy: 0.8254 - loss: 0.4317
Epoch 6/200
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 826us/step - accuracy: 0.8364 - loss: 0.4132
Epoch 7/200
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 812us/step - accuracy: 0.8311 - loss: 0.4167
Epoch 8/200
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 832us/step - accuracy: 0.8378 - loss: 0.3987
Epoch 9/200
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 821us/step - accuracy: 0.8388 - loss: 0.4083
Epoch 10/200
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 846us/step - accuracy: 0.8388 - loss: 0.3983
Epoch 11/200
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 805us/step - accuracy: 0.8370 - loss: 0.4071
Epoch 12/200
800/80

In [36]:
# optimizers - forward prpo backward propogation handler
#making predictions and model evaluation
y_pred_ann = classifier.predict(x_test)
y_pred_ann = (y_pred_ann > 0.5)

cm3 = confusion_matrix(y_test, y_pred_ann)
print(cm3)
accuracy_score(y_test,y_pred_ann)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step  
[[1532   63]
 [ 212  193]]


0.8625

**Conclusion**

so as we expected we have alredy seen by using 2 hidden layer ann , we arent get byond 85/86% acc , offcourse we can get acc high by performing hyperparameter tuning and by increasing epoches in other hand classical models can also be tuned further .

Bottomline , always start with classical ml models and if arent able to increase performance then try or move towards deeplearning techniques


**Hyperparameter tuning** - step that we perform after our basic model is created after feature enggineearing and feature scaling is done , basically tweaking hyper parameters  identifies what are best possible combinations of hyper parameter that we have which will be best for our model



**Hyperparameters optimizations options** - manuals - means caling models repetaytely by changing optimizers - adam , rmsprop etc manual way of doing it  , randomisedsearchCV - defin paramgrid like opt = [adams rmsprop etc ] then epoch =[5,10,50,100] n_iters - means 5 combinations of params will run and nbased on that we will get best params , GridsearchCV - runing each and every combinations
